---
galaxy_info:
  author: Riccardo Magliocchetti
  description: Deploy LabAdmin
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
      - trusty
      - xenial
  - name: Debian
    versions:
      - jessie
      - stretch
  - galaxy_tags:
    - web
  dependencies: []
